name: Stack Hosted Cloud PubSub Test
on: [push]
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: "3.3.1"
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/3367369000/locations/global/workloadIdentityPools/wip-github-yqou/providers/wip-provider-github
          service_account: sa-ci-cloud-pubsub@proda-ci.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
          universe: googleapis.com
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          id_token_include_email: false
      - name: Cache Stack Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml', 'stack.yaml.lock') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            - ${{ runner.os }}-${{ hashFiles('stack.yaml', 'stack.yaml.lock') }}-${{ hashFiles('package.yaml') }}
            - ${{ runner.os }}-${{ hashFiles('stack.yaml', 'stack.yaml.lock') }}
            - ${{ runner.os }}-
      - name: Install Dependencies
        run: stack install --only-dependencies --test
      - name: Run Tests
        run: stack test
        env:
          PROJECT_ID: ${{secrets.PROJECT_ID}}
